{
//=========Macro generated from canvas: Poisson_Example_Plot/title
//=========  (Sun Sep 11 19:25:47 2016) by ROOT version5.34/36
   TCanvas *Poisson_Example_Plot = new TCanvas("Poisson_Example_Plot", "title",0,22,630,604);
   gStyle->SetOptFit(1);
   gStyle->SetOptTitle(0);
   Poisson_Example_Plot->Range(47.76698,-0.006429789,521.8147,0.03643547);
   Poisson_Example_Plot->SetFillColor(0);
   Poisson_Example_Plot->SetBorderMode(0);
   Poisson_Example_Plot->SetBorderSize(2);
   Poisson_Example_Plot->SetTickx(1);
   Poisson_Example_Plot->SetTicky(1);
   Poisson_Example_Plot->SetLeftMargin(0.18);
   Poisson_Example_Plot->SetBottomMargin(0.15);
   Poisson_Example_Plot->SetFrameFillStyle(0);
   Poisson_Example_Plot->SetFrameBorderMode(0);
   Poisson_Example_Plot->SetFrameFillStyle(0);
   Poisson_Example_Plot->SetFrameBorderMode(0);
   
   TH1F *temphisto = new TH1F("temphisto","",100,133.0956,474.4099);
   temphisto->SetMinimum(0);
   temphisto->SetMaximum(0.03214894);
   temphisto->SetStats(0);
   temphisto->SetLineStyle(0);
   temphisto->SetMarkerStyle(20);
   temphisto->GetXaxis()->SetTitle(" Count");
   temphisto->GetXaxis()->SetLabelFont(42);
   temphisto->GetXaxis()->SetLabelOffset(0.007);
   temphisto->GetXaxis()->SetLabelSize(0.045);
   temphisto->GetXaxis()->SetTitleSize(0.05);
   temphisto->GetXaxis()->SetTitleOffset(1.5);
   temphisto->GetXaxis()->SetTitleFont(42);
   temphisto->GetYaxis()->SetTitle(" Probability per Count");
   temphisto->GetYaxis()->SetLabelFont(42);
   temphisto->GetYaxis()->SetLabelOffset(0.007);
   temphisto->GetYaxis()->SetLabelSize(0.045);
   temphisto->GetYaxis()->SetTitleSize(0.05);
   temphisto->GetYaxis()->SetTitleOffset(1.8);
   temphisto->GetYaxis()->SetTitleFont(42);
   temphisto->GetZaxis()->SetLabelFont(42);
   temphisto->GetZaxis()->SetLabelOffset(0.007);
   temphisto->GetZaxis()->SetLabelSize(0.05);
   temphisto->GetZaxis()->SetTitleSize(0.06);
   temphisto->GetZaxis()->SetTitleFont(42);
   temphisto->Draw("");
   
   TPaveText *pt = new TPaveText(0.17,0.88,0.45,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->SetTextSize(0.03);
   TText *text = pt->AddText("DELPHES simulation                               #sqrt{s} = 13 TeV, L = 100 fb^{-1}");
   pt->Draw();
   
   pt = new TPaveText(0.64,0.88,0.92,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(42);
   pt->Draw();
   
   TF1 *poisson_left_pink = new TF1("poisson_left_pink","TMath::Poisson(x*[1],[0])/[2]",0,1000);
   poisson_left_pink->SetFillColor(6);
   poisson_left_pink->SetFillStyle(3004);
   poisson_left_pink->SetLineColor(6);
   poisson_left_pink->SetLineWidth(3);
   poisson_left_pink->SetLineStyle(2);
   poisson_left_pink->GetXaxis()->SetLabelFont(42);
   poisson_left_pink->GetXaxis()->SetLabelOffset(0.007);
   poisson_left_pink->GetXaxis()->SetLabelSize(0.05);
   poisson_left_pink->GetXaxis()->SetTitleSize(0.06);
   poisson_left_pink->GetXaxis()->SetTitleOffset(0.9);
   poisson_left_pink->GetXaxis()->SetTitleFont(42);
   poisson_left_pink->GetYaxis()->SetLabelFont(42);
   poisson_left_pink->GetYaxis()->SetLabelOffset(0.007);
   poisson_left_pink->GetYaxis()->SetLabelSize(0.05);
   poisson_left_pink->GetYaxis()->SetTitleSize(0.06);
   poisson_left_pink->GetYaxis()->SetTitleOffset(1.25);
   poisson_left_pink->GetYaxis()->SetTitleFont(42);
   poisson_left_pink->SetParameter(0,316.2733);
   poisson_left_pink->SetParError(0,0);
   poisson_left_pink->SetParLimits(0,0,0);
   poisson_left_pink->SetParameter(1,1);
   poisson_left_pink->SetParError(1,0);
   poisson_left_pink->SetParLimits(1,0,0);
   poisson_left_pink->SetParameter(2,1);
   poisson_left_pink->SetParError(2,0);
   poisson_left_pink->SetParLimits(2,0,0);
   poisson_left_pink->Draw("same");
   
   TF1 *poisson_right_blue = new TF1("poisson_right_blue","TMath::Poisson(x*[1],[0])/[2]",0,1000);
   poisson_right_blue->SetFillColor(9);
   poisson_right_blue->SetFillStyle(3005);
   poisson_right_blue->SetLineColor(9);
   poisson_right_blue->SetLineWidth(3);
   poisson_right_blue->SetLineStyle(2);
   poisson_right_blue->GetXaxis()->SetLabelFont(42);
   poisson_right_blue->GetXaxis()->SetLabelOffset(0.007);
   poisson_right_blue->GetXaxis()->SetLabelSize(0.05);
   poisson_right_blue->GetXaxis()->SetTitleSize(0.06);
   poisson_right_blue->GetXaxis()->SetTitleOffset(0.9);
   poisson_right_blue->GetXaxis()->SetTitleFont(42);
   poisson_right_blue->GetYaxis()->SetLabelFont(42);
   poisson_right_blue->GetYaxis()->SetLabelOffset(0.007);
   poisson_right_blue->GetYaxis()->SetLabelSize(0.05);
   poisson_right_blue->GetYaxis()->SetTitleSize(0.06);
   poisson_right_blue->GetYaxis()->SetTitleOffset(1.25);
   poisson_right_blue->GetYaxis()->SetTitleFont(42);
   poisson_right_blue->SetParameter(0,221.826);
   poisson_right_blue->SetParError(0,0);
   poisson_right_blue->SetParLimits(0,0,0);
   poisson_right_blue->SetParameter(1,1);
   poisson_right_blue->SetParError(1,0);
   poisson_right_blue->SetParLimits(1,0,0);
   poisson_right_blue->SetParameter(2,1);
   poisson_right_blue->SetParError(2,0);
   poisson_right_blue->SetParLimits(2,0,0);
   poisson_right_blue->Draw("same");
   TLine *line = new TLine(221.826,0,221.826,0.03214894);
   line->SetLineColor(9);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   line = new TLine(316.2733,0,316.2733,0.03214894);
   line->SetLineColor(6);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TLegend *leg = new TLegend(0.65,0.7,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(1);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = 924;
   color = new TColor(ci, 0, 0, 0, " ", 0);
   leg->SetLineColor(ci);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);

   ci = TColor::GetColor("#ffffff");
   leg->SetFillColor(ci);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("poisson_left_pink","LH Model","LF");
   entry->SetFillColor(6);
   entry->SetFillStyle(3004);
   entry->SetLineColor(6);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("poisson_right_blue","RH Model","LF");
   entry->SetFillColor(9);
   entry->SetFillStyle(3005);
   entry->SetLineColor(9);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("poisson_full_red","M3","LF");
   entry->SetFillColor(2);
   entry->SetFillStyle(3006);
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   line = new TLine(271.6013,0,271.6013,0.03214894);
   line->SetLineColor(2);
   line->SetLineStyle(2);
   line->SetLineWidth(3);
   line->Draw();
   
   TF1 *poisson_full_red = new TF1("poisson_full_red","TMath::Poisson(x*[1],[0])/[2]",0,1000);
   poisson_full_red->SetFillColor(2);
   poisson_full_red->SetFillStyle(3006);
   poisson_full_red->SetLineColor(2);
   poisson_full_red->SetLineWidth(3);
   poisson_full_red->SetLineStyle(2);
   poisson_full_red->GetXaxis()->SetLabelFont(42);
   poisson_full_red->GetXaxis()->SetLabelOffset(0.007);
   poisson_full_red->GetXaxis()->SetLabelSize(0.05);
   poisson_full_red->GetXaxis()->SetTitleSize(0.06);
   poisson_full_red->GetXaxis()->SetTitleOffset(0.9);
   poisson_full_red->GetXaxis()->SetTitleFont(42);
   poisson_full_red->GetYaxis()->SetLabelFont(42);
   poisson_full_red->GetYaxis()->SetLabelOffset(0.007);
   poisson_full_red->GetYaxis()->SetLabelSize(0.05);
   poisson_full_red->GetYaxis()->SetTitleSize(0.06);
   poisson_full_red->GetYaxis()->SetTitleOffset(1.25);
   poisson_full_red->GetYaxis()->SetTitleFont(42);
   poisson_full_red->SetParameter(0,271.6013);
   poisson_full_red->SetParError(0,0);
   poisson_full_red->SetParLimits(0,0,0);
   poisson_full_red->SetParameter(1,1);
   poisson_full_red->SetParError(1,0);
   poisson_full_red->SetParLimits(1,0,0);
   poisson_full_red->SetParameter(2,1);
   poisson_full_red->SetParError(2,0);
   poisson_full_red->SetParLimits(2,0,0);
   poisson_full_red->Draw("same");
   
   leg = new TLegend(0.65,0.7,0.89,0.85,NULL,"brNDC");
   leg->SetBorderSize(1);

   ci = 924;
   color = new TColor(ci, 0, 0, 0, " ", 0);
   leg->SetLineColor(ci);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);

   ci = TColor::GetColor("#ffffff");
   leg->SetFillColor(ci);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("poisson_left_pink","LH Model","LF");
   entry->SetFillColor(6);
   entry->SetFillStyle(3004);
   entry->SetLineColor(6);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("poisson_right_blue","RH Model","LF");
   entry->SetFillColor(9);
   entry->SetFillStyle(3005);
   entry->SetLineColor(9);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("poisson_full_red","M3","LF");
   entry->SetFillColor(2);
   entry->SetFillStyle(3006);
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Poisson_Example_Plot->Modified();
   Poisson_Example_Plot->cd();
   Poisson_Example_Plot->SetSelected(Poisson_Example_Plot);
}
